"""Deterministic audit checks for authenticity measurement.

These checks identify NPC patterns and low-authenticity artifacts:
- Template reuse
- Persona declarations
- Round-robin scheduling
- Forced disagreement
- Belief resets
- Unsupported claims
- Private state leakage
"""

import re
import json
from collections import Counter, defaultdict
from typing import List, Dict, Tuple


# Patterns for common NPC artifacts
GENERIC_OPENERS = [
    r"this one really caught my attention",
    r"this paper really caught my eye",
    r"this caught my attention",
    r"this is fascinating",
    r"interesting work",
    r"compelling research",
    r"this is compelling",
    r"quite elegant",
    r"the \w+ framework.*is quite elegant",
    r"the mathematical framework",
    r"the engineering pragmatism",
    r"the storytelling in how they frame",
]

PERSONA_DECLARATIONS = [
    r"(?:i|i'm|as a|being) (?:hal|ada|vera)",
    r"(?:hal|ada|vera) here",
    r"speaking as (?:hal|ada|vera)",
    r"from my perspective as",
    r"i'm the one who",
]

RITUAL_CONCESSIONS = [
    r"fair point",
    r"that's a fair point",
    r"good catch",
    r"fair enough",
    r"you're right",
    r"i concede",
    r"you make a good point",
    r"i see your point",
]

FORCED_TRANSITION_PATTERNS = [
    r"(?:hal|ada|vera), what do you think",
    r"(?:hal|ada|vera), your thoughts",
    r"moving on to",
    r"let's talk about",
    r"turning to",
    r"next,",
]

FILLER_PHRASES = [
    r"in summary",
    r"to summarize",
    r"in conclusion",
    r"broadly speaking",
    r"ultimately",
    r"at the end of the day",
    r"in short",
]

UNSUPPORTED_CLAIM_MARKERS = [
    r"obviously",
    r"clearly",
    r"as we all know",
    r"it's well known",
    r"everyone knows",
    r"it's obvious that",
    r"no doubt that",
]

FALLBACK_TEMPLATE_MARKERS = [
    r"\[GENERATED BY LLM\]",
    r"\[FALLBACK\]",
    r"\[DEFAULT\]",
    r"\[PLACEHOLDER\]",
]


def find_generic_openers(text: str, character: str = None) -> List[Tuple[int, str]]:
    """Find instances of generic opening phrases.

    Returns:
        List of (occurrence_count, phrase) tuples
    """
    matches = []
    text_lower = text.lower()

    for pattern in GENERIC_OPENERS:
        for match in re.finditer(pattern, text_lower, re.IGNORECASE):
            matches.append((match.start(), match.group()))

    return sorted(matches, key=lambda x: x[0])


def find_persona_declarations(text: str) -> List[Tuple[int, str]]:
    """Find instances of hosts explicitly declaring their identity."""
    matches = []
    text_lower = text.lower()

    for pattern in PERSONA_DECLARATIONS:
        for match in re.finditer(pattern, text_lower, re.IGNORECASE):
            matches.append((match.start(), match.group()))

    return sorted(matches, key=lambda x: x[0])


def find_round_robin_markers(lines: List[str]) -> List[str]:
    """Detect scheduled round-robin turn patterns.

    If hosts alternate in strict order (Hal → Ada → VERA → Hal),
    that's likely round-robin scheduling.

    Returns:
        List of failure tags
    """
    tags = []
    hosts_in_order = []

    for line in lines:
        for host in ["Hal", "Ada", "VERA"]:
            if line.startswith(f"{host}:") or line.startswith(f"**{host}:**"):
                hosts_in_order.append(host)
                break

    if len(hosts_in_order) >= 6:
        # Check for strict rotation
        expected_rotation = ["Hal", "Ada", "VERA"]
        rotation_count = 0
        for i in range(len(hosts_in_order) - 2):
            if hosts_in_order[i:i+3] == expected_rotation:
                rotation_count += 1

        if rotation_count >= 2:
            tags.append("ROUND_ROBIN")

    return tags


def find_forced_transitions(text: str) -> List[Tuple[int, str]]:
    """Find instances of forced speaker transitions."""
    matches = []

    for pattern in FORCED_TRANSITION_PATTERNS:
        for match in re.finditer(pattern, text, re.IGNORECASE):
            matches.append((match.start(), match.group()))

    return sorted(matches, key=lambda x: x[0])


def find_ritual_concessions(text: str) -> List[Tuple[int, str]]:
    """Find instances of ritual concessions without real state change.

    These are quick agreeing phrases that don't actually update the
    host's belief state for the next turn.
    """
    matches = []
    text_lower = text.lower()

    for pattern in RITUAL_CONCESSIONS:
        for match in re.finditer(pattern, text_lower, re.IGNORECASE):
            matches.append((match.start(), match.group()))

    return sorted(matches, key=lambda x: x[0])


def detect_airtime_imbalance(lines: List[str]) -> Tuple[Dict[str, int], str]:
    """Analyze airtime distribution across hosts.

    Returns:
        (airtime_dict, failure_tag) where tag is "" if balanced,
        or one of: "UNEQUAL_AIRTIME", "ORNAMENTAL_HOST"
    """
    host_lines = {"Hal": 0, "Ada": 0, "VERA": 0}

    for line in lines:
        for host in host_lines:
            if line.startswith(f"{host}:") or line.startswith(f"**{host}:**"):
                host_lines[host] += 1
                break

    total = sum(host_lines.values())
    if total == 0:
        return host_lines, ""

    # Expected: ~1/3 each
    expected = total / 3
    tolerance = 0.15

    airtime_ratios = {h: c / total for h, c in host_lines.items()}
    imbalanced = any(
        abs(ratio - (1/3)) > tolerance
        for ratio in airtime_ratios.values()
    )

    if imbalanced:
        # Check if anyone is purely ornamental (<10% but present)
        silent = [h for h, c in host_lines.items() if c == 0]
        minimal = [h for h, c in host_lines.items() if 0 < c < max(1, total // 10)]

        if minimal and len(minimal) <= 1:
            return host_lines, "ORNAMENTAL_HOST"
        return host_lines, "UNEQUAL_AIRTIME"

    return host_lines, ""


def find_paper_substitutability(text: str) -> List[str]:
    """Check if dialogue would work with a different paper.

    Looks for:
    - Lack of specific evidence references
    - Generic conclusions
    - Missing paper-specific details
    """
    tags = []

    # Count specific references (arxiv IDs, author names, equations, proofs)
    arxiv_refs = len(re.findall(r'\d{4}\.\d{4,5}', text))
    claim_refs = len(re.findall(r'(claim|theorem|equation|proof|result|finding)', text, re.IGNORECASE))
    evidence_refs = len(re.findall(r'(shows|demonstrates|proves|finds|observes|reports)', text, re.IGNORECASE))

    total_references = arxiv_refs + claim_refs + evidence_refs
    lines = text.split('\n')
    avg_refs_per_line = total_references / len(lines) if lines else 0

    if avg_refs_per_line < 0.5:  # Less than 1 reference per 2 lines
        tags.append("PAPER_SUBSTITUTABLE")

    return tags


def find_private_state_leakage(text: str) -> List[Tuple[int, str]]:
    """Detect references to private research or unpublished work.

    The podcast should ONLY discuss the paper's own published content,
    not the operator's private research.
    """
    matches = []
    suspicious_patterns = [
        r"(?:our|our team's|our recent) (?:work|research|project|experiment)",
        r"(?:we|us) recently (?:found|discovered|built|showed)",
        r"(?:in our|in our earlier) (?:work|study|paper)",
        r"unpublished (?:results|data|findings)",
        r"(?:proprietary|internal) (?:framework|methodology|approach)",
    ]

    for pattern in suspicious_patterns:
        for match in re.finditer(pattern, text, re.IGNORECASE):
            matches.append((match.start(), match.group()))

    return sorted(matches, key=lambda x: x[0])


def find_unsupported_claims(text: str) -> List[Tuple[int, str]]:
    """Find claims marked with empty hedges (obviously, clearly, etc)."""
    matches = []

    for pattern in UNSUPPORTED_CLAIM_MARKERS:
        for match in re.finditer(pattern, text, re.IGNORECASE):
            # Get context (next 50 chars)
            start = match.start()
            end = min(match.end() + 50, len(text))
            context = text[start:end]
            matches.append((start, context.strip()))

    return sorted(matches, key=lambda x: x[0])


def find_template_artifacts(text: str) -> List[str]:
    """Find explicit template markers or fallback indicators."""
    matches = []

    for pattern in FALLBACK_TEMPLATE_MARKERS:
        if re.search(pattern, text, re.IGNORECASE):
            matches.append(pattern)

    return matches


def audit_episode(transcript: str, lines: List[str] = None) -> Dict[str, any]:
    """Run full audit suite on an episode transcript.

    Args:
        transcript: Full episode text
        lines: Pre-split lines (optional optimization)

    Returns:
        Dict with audit results and failure tags
    """
    if lines is None:
        lines = transcript.split('\n')

    results = {
        "generic_openers": find_generic_openers(transcript),
        "persona_declarations": find_persona_declarations(transcript),
        "round_robin_markers": find_round_robin_markers(lines),
        "forced_transitions": find_forced_transitions(transcript),
        "ritual_concessions": find_ritual_concessions(transcript),
        "airtime": detect_airtime_imbalance(lines),
        "paper_substitutable": find_paper_substitutability(transcript),
        "private_state_leakage": find_private_state_leakage(transcript),
        "unsupported_claims": find_unsupported_claims(transcript),
        "template_artifacts": find_template_artifacts(transcript),
    }

    # Aggregate failure tags
    all_tags = []
    all_tags.extend(results["round_robin_markers"])
    all_tags.extend(results["paper_substitutable"])
    all_tags.extend(results["template_artifacts"])

    if results["airtime"][1]:
        all_tags.append(results["airtime"][1])
    if results["generic_openers"]:
        all_tags.append("GENERIC_OPENER")
    if results["persona_declarations"]:
        all_tags.append("PERSONA_DECLARATION")
    if results["forced_transitions"]:
        all_tags.append("FORCED_TRANSITION")
    if results["ritual_concessions"]:
        all_tags.append("RITUAL_CONCESSION")
    if results["private_state_leakage"]:
        all_tags.append("PRIVATE_STATE_LEAKAGE")
    if results["unsupported_claims"]:
        all_tags.append("UNSUPPORTED_CLAIM")

    results["failure_tags"] = list(set(all_tags))
    results["severity_count"] = len(all_tags)

    return results
