name = "podcast-admin"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "c6cd84b0ad169e7e8e46f41ee960024a"
routes = [
  { pattern = "admin.podcast.do-not-panic.com/*", zone_id = "bfc13a7f8c9c796b1fc23083c8b83310" }
]

[[r2_buckets]]
binding = "ADMIN_BUCKET"
bucket_name = "podcast-admin"

[[r2_buckets]]
binding = "PODCAST_BUCKET"
bucket_name = "ai-post-transformers"
